name: vector_graphics_plus
description: A vector graphics rendering package for Flutter.
version: 1.1.13
homepage: https://github.com/nank1ro/vector_graphics

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.5.0-0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  vector_graphics_codec: ^1.1.11+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  vector_graphics_compiler_plus: ^1.1.12

# Comment out before publishing
dependency_overrides:
  vector_graphics_codec:
    path: ../vector_graphics_codec
  vector_graphics_compiler_plus:
    path: ../vector_graphics_compiler

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
