name: example
description: An example of the vector_graphics package
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: any
  flutter:
    sdk: flutter
  vector_graphics_plus: any
  vector_graphics_compiler_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  vector_graphics_compiler_plus:
    path: ../../vector_graphics_compiler
  vector_graphics_codec:
    path: ../../vector_graphics_codec
  vector_graphics_plus:
    path: ../

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
